name: SRE Pipeline

on:
  push:
    branches: [ "main" ] # Runs every time you push to main

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    # This gives the robot permission to write to your GitHub Package store
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This names your image: ghcr.io/your-username/repo-name:latest
          tags: ghcr.io/${{ github.repository }}:latest
